#This script will take as input the *.fa files that were generated by biotiger using -f 4 and will add the site number to the charset needed in nexus for AMAS

import os

file_list = []

for files in os.listdir("mafft_aligned/"):
	name = files.split(".")[0]
	if name not in file_list:
		file_list.append(name)

for file_names in file_list:
        bins_dict = {}
	for files in os.listdir("mafft_aligned/"):
		if files.startswith(file_names):
			if files.endswith(".fa"):
                                bins = files.split(".")
                                print bins
                                bin_name = bins[2]
                                with open("mafft_aligned/"+files) as fa_file:
                                        secondline = fa_file.readlines()[1:2]
#                                        print secondline
                                        counts = 0
                                        for x in secondline[0]:
                                                counts+=1
                                                if x == "X":
                                                        pass
                                                else:
                                                        if bin_name in bins_dict:
                                                                bins_dict[bin_name].append(counts)
                                                        if bin_name not in bins_dict:
                                                                bins_dict[bin_name] = [counts]
				fa_file.close()
	partition_name = file_names+"_partition.txt"
	part_file = open("mafft_aligned/"+partition_name, 'a')
	for key, value in bins_dict.iteritems():
		char_line = key.strip()+"="
		for x in value:
			char_line+=str(x)+", "
		print >>part_file, char_line
	part_file.close()
