#This script will be used to create the sensitivity anaylsis figure with ggtree

library(ape)
library(ggtree)
library(ggplot2)
library(dplyr)
library(ggimage)

ml_data <- read.nexus("Phylo_correct_topology.tre")

ml_tree <- ggtree::ggtree(ml_data, branch.length='none') #+ geom_tiplab()

raxml_nodes <- data.frame(node = c(49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,
                                   73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94),
                          images = c("~/Documents/Research/My_TOAST_Project/RAxML_node1.png","~/Documents/Research/My_TOAST_Project/RAxML_node2.png","~/Documents/Research/My_TOAST_Project/RAxML_node3.png","~/Documents/Research/My_TOAST_Project/RAxML_node4.png","~/Documents/Research/My_TOAST_Project/RAxML_node5.png","~/Documents/Research/My_TOAST_Project/RAxML_node6.png","~/Documents/Research/My_TOAST_Project/RAxML_node7.png","~/Documents/Research/My_TOAST_Project/RAxML_node8.png","~/Documents/Research/My_TOAST_Project/RAxML_node9.png","~/Documents/Research/My_TOAST_Project/RAxML_node10.png",                                     
                                     "~/Documents/Research/My_TOAST_Project/RAxML_node11.png","~/Documents/Research/My_TOAST_Project/RAxML_node12.png","~/Documents/Research/My_TOAST_Project/RAxML_node13.png","~/Documents/Research/My_TOAST_Project/RAxML_node14.png","~/Documents/Research/My_TOAST_Project/RAxML_node15.png","~/Documents/Research/My_TOAST_Project/RAxML_node16.png","~/Documents/Research/My_TOAST_Project/RAxML_node17.png","~/Documents/Research/My_TOAST_Project/RAxML_node18.png","~/Documents/Research/My_TOAST_Project/RAxML_node19.png","~/Documents/Research/My_TOAST_Project/RAxML_node20.png",
                                    "~/Documents/Research/My_TOAST_Project/RAxML_node21.png","~/Documents/Research/My_TOAST_Project/RAxML_node22.png","~/Documents/Research/My_TOAST_Project/RAxML_node23.png","~/Documents/Research/My_TOAST_Project/RAxML_node24.png","~/Documents/Research/My_TOAST_Project/RAxML_node25.png","~/Documents/Research/My_TOAST_Project/RAxML_node26.png","~/Documents/Research/My_TOAST_Project/RAxML_node27.png","~/Documents/Research/My_TOAST_Project/RAxML_node28.png","~/Documents/Research/My_TOAST_Project/RAxML_node29.png","~/Documents/Research/My_TOAST_Project/RAxML_node30.png",
                                     "~/Documents/Research/My_TOAST_Project/RAxML_node31.png","~/Documents/Research/My_TOAST_Project/RAxML_node32.png","~/Documents/Research/My_TOAST_Project/RAxML_node33.png","~/Documents/Research/My_TOAST_Project/RAxML_node34.png","~/Documents/Research/My_TOAST_Project/RAxML_node35.png","~/Documents/Research/My_TOAST_Project/RAxML_node36.png","~/Documents/Research/My_TOAST_Project/RAxML_node37.png","~/Documents/Research/My_TOAST_Project/RAxML_node38.png","~/Documents/Research/My_TOAST_Project/RAxML_node39.png","~/Documents/Research/My_TOAST_Project/RAxML_node40.png",
                                     "~/Documents/Research/My_TOAST_Project/RAxML_node41.png","~/Documents/Research/My_TOAST_Project/RAxML_node42.png","~/Documents/Research/My_TOAST_Project/RAxML_node43.png","~/Documents/Research/My_TOAST_Project/RAxML_node44.png","~/Documents/Research/My_TOAST_Project/RAxML_node45.png","~/Documents/Research/My_TOAST_Project/RAxML_node46.png"))

raxml_nodes <- data.frame(node=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,
                                 27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,
                                 50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,
                                 73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94),
                          images=c("~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png",
                                   "~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png",
                                   "~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png",
                                   "~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png",
                                   "~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png","~/Documents/Research/My_TOAST_Project/white.png",
                                   "~/Documents/Research/My_TOAST_Project/RAxML_node1.png","~/Documents/Research/My_TOAST_Project/RAxML_node2.png","~/Documents/Research/My_TOAST_Project/RAxML_node3.png","~/Documents/Research/My_TOAST_Project/RAxML_node4.png","~/Documents/Research/My_TOAST_Project/RAxML_node5.png","~/Documents/Research/My_TOAST_Project/RAxML_node6.png","~/Documents/Research/My_TOAST_Project/RAxML_node7.png","~/Documents/Research/My_TOAST_Project/RAxML_node8.png","~/Documents/Research/My_TOAST_Project/RAxML_node9.png","~/Documents/Research/My_TOAST_Project/RAxML_node10.png",
                                   "~/Documents/Research/My_TOAST_Project/RAxML_node11.png","~/Documents/Research/My_TOAST_Project/RAxML_node12.png","~/Documents/Research/My_TOAST_Project/RAxML_node13.png","~/Documents/Research/My_TOAST_Project/RAxML_node14.png","~/Documents/Research/My_TOAST_Project/RAxML_node15.png","~/Documents/Research/My_TOAST_Project/RAxML_node16.png","~/Documents/Research/My_TOAST_Project/RAxML_node17.png","~/Documents/Research/My_TOAST_Project/RAxML_node18.png","~/Documents/Research/My_TOAST_Project/RAxML_node19.png","~/Documents/Research/My_TOAST_Project/RAxML_node20.png",
                                   "~/Documents/Research/My_TOAST_Project/RAxML_node21.png","~/Documents/Research/My_TOAST_Project/RAxML_node22.png","~/Documents/Research/My_TOAST_Project/RAxML_node23.png","~/Documents/Research/My_TOAST_Project/RAxML_node24.png","~/Documents/Research/My_TOAST_Project/RAxML_node25.png","~/Documents/Research/My_TOAST_Project/RAxML_node26.png","~/Documents/Research/My_TOAST_Project/RAxML_node27.png","~/Documents/Research/My_TOAST_Project/RAxML_node28.png","~/Documents/Research/My_TOAST_Project/RAxML_node29.png","~/Documents/Research/My_TOAST_Project/RAxML_node30.png",
                                   "~/Documents/Research/My_TOAST_Project/RAxML_node31.png","~/Documents/Research/My_TOAST_Project/RAxML_node32.png","~/Documents/Research/My_TOAST_Project/RAxML_node33.png","~/Documents/Research/My_TOAST_Project/RAxML_node34.png","~/Documents/Research/My_TOAST_Project/RAxML_node35.png","~/Documents/Research/My_TOAST_Project/RAxML_node36.png","~/Documents/Research/My_TOAST_Project/RAxML_node37.png","~/Documents/Research/My_TOAST_Project/RAxML_node38.png","~/Documents/Research/My_TOAST_Project/RAxML_node39.png","~/Documents/Research/My_TOAST_Project/RAxML_node40.png",
                                   "~/Documents/Research/My_TOAST_Project/RAxML_node41.png","~/Documents/Research/My_TOAST_Project/RAxML_node42.png","~/Documents/Research/My_TOAST_Project/RAxML_node43.png","~/Documents/Research/My_TOAST_Project/RAxML_node44.png","~/Documents/Research/My_TOAST_Project/RAxML_node45.png","~/Documents/Research/My_TOAST_Project/RAxML_node46.png"))

#ml_tree %<+% raxml_nodes +geom_nodelab(aes(image=images),geom="image")
#ggtree::ggtree(ml_data, branch.length='none') %<+% raxml_nodes + ggtree::geom_nodelab(aes(image=images),geom="image")
ml_sens_fig <- ggtree::ggtree(ml_data,branch.length = 'none') %<+% raxml_nodes +ggtree::geom_nodelab(aes(image=images),geom="image")
png(file="RAxML_sensitivity_figure.png")
print(ml_sens_fig)


#### ASTRAL SENSITIVITY FIGURE ####

astral_data <- read.nexus("Astral_correct_topology.tre")
astral_tree <- ggtree::ggtree(astral_data, branch.length='none')
astral_nodes <- data.frame(node = c("49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69",
                                   "70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90",
                                   "91","92","93","94","95"),
                          images = c("~/Documents/Research/My_TOAST_Project/ASTRAL_node1.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node2.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node3.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node4.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node5.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node6.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node7.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node8.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node9.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node10.png",
                                     "~/Documents/Research/My_TOAST_Project/ASTRAL_node11.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node12.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node13.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node14.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node15.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node16.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node17.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node18.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node19.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node20.png",
                                     "~/Documents/Research/My_TOAST_Project/ASTRAL_node21.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node22.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node23.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node24.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node25.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node26.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node27.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node28.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node29.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node30.png",
                                     "~/Documents/Research/My_TOAST_Project/ASTRAL_node31.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node32.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node33.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node34.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node35.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node36.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node37.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node38.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node39.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node40.png",
                                     "~/Documents/Research/My_TOAST_Project/ASTRAL_node41.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node42.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node43.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node44.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node45.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node46.png","~/Documents/Research/My_TOAST_Project/ASTRAL_node47.png"))
astral_tree + geom_text(aes(label=node))
astral_nodes$node <- as.numeric(astral_nodes$node)
#astral_tree <- ggtree::rotate(astral_tree,55)+scale_x_reverse()
#astral_sens_fig <- ggtree::ggtree(astral_data,branch.length = 'none') %<+% astral_nodes +ggtree::geom_nodelab(aes(image=images),geom="image")
#png(file="Astral_sensitivity_figure.png")
#print(astral_sens_fig)

for (i in 1:length(astral_nodes$node)){
  imgfile <- astral_nodes$images[i]
  astral_tree <- astral_tree + geom_nodelab(node=i,imgfile,geom="image")
}

